### ISSUE TITLE
`google_hotels` source incorrect documentation

### ISSUE THREAD

**Issue by UmanShahzad** [oxylabs/oxylabs-sdk-go#6]
In this point from @Ryouku 's message:

> 7. google_hotels source doesn’t actually have results_language param. This should be passed via context:results_language instead.

There's a mistake in the documentation, as it contains the `results_language` param (as well as the `context:`-prefixed one). We'll remove it from the code but the docs need a fix?

@efgh5678 is this your domain?

**Comment by UmanShahzad** [comment]
Was there any update on this, @efgh5678 @Ryouku

**Comment by maaz-munir** [comment]
Thanks @denis-zyk. I checked the docs, it has been fixed.

While we're on this, I noticed the `parse` parameter option for `bing*` sources is missing from the docs [here](https://developers.oxylabs.io/scraper-apis/serp-scraper-api/bing). Could you check that out as well?

**Comment by denis-zyk** [comment]
@maaz-munir nice catch! I've passed the info, the docs will be fixed soon.

**Comment by oxy-gerach** [comment]
Docs are fixed, this should be closed.

**Comment by oxy-zy** [comment]
Docs has ben updated.
